entities:
  - name: Countries
    primaryKey:
      - iso3
    uniqueKey:
      - name
    properties:
      - name: name
        nullable: false
      - name: iso3
        nullable: false
        length: 3
    relations:
      - name: states
        type: manyToOne
        composite: true
        from: iso3
        entity: States
        to: countryCode
  - name: States
    primaryKey:
      - id
    uniqueKey:
      - countryCode
      - name
    properties:
      - name: id
        type: integer
        nullable: false
      - name: name
        nullable: false
      - name: countryCode
        nullable: false
        length: 3
    relations:
      - name: country
        from: countryCode
        entity: Countries
        to: iso3
mappings:
  - name: default
sources:
  - name: db1
    dialect: MySQL
    mapping: default
    connection: ${CNN_MySQL}
stages:
  - name: default
    sources:
      - name: db1
app:
  src: src
  data: data
  model: model
enums: []
