version: "3"

services:
  db:
    container_name: devicenet-postgres-cli-lab
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=devicenet
      - POSTGRES_USER=devicenet
      - POSTGRES_PASSWORD=devicenet
    volumes:
      - ./volume/Postgres-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
