name: Develop
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      # - name: Unit Tests
      #   run: npm run unit-test
